config = {
    "data": {
        "source": "imdb"
    },
    "model": {
        "type": "lstm",
        "vocab_size": 5000,
        "embed_dim": 128,
        "hidden_dim": 128,
        "num_classes": 2
    },
    "training": {
        "lr": 0.001,
        "batch_size": 2,
        "epochs": 3
    }
}